version: "3.9"
services:
  db:
    image: postgres:15
    container_name: hr_assistant_db
    environment:
      POSTGRES_DB: adk_hr_db
      POSTGRES_USER: adk_user
      POSTGRES_PASSWORD: adk_password
    ports:
      - "5433:5432"  # Host port 5433 -> Container's Postgres 5432 (avoid local conflict)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adk_user -d adk_hr_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: hr_assistant_app
    ports:
      - "8007:8007"  # Host port 8001 -> Agent service (includes Web UI at /dev-ui)
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # Mount source code for hot-reloading (optional in development)
      - ./hr_recruiting_assistant:/app/hr_recruiting_assistant
      - ./api.py:/app/api.py
      # Mount Google Cloud credentials for model access (read-only)
      - type: bind
        source: ${APPDATA:-~/.config}/gcloud
        target: /root/.config/gcloud
        read_only: true
    stdin_open: true   # Keep STDIN open (needed if using uvicorn reload)
    tty: true          # Allocate a pseudo-TTY (needed for uvicorn reload)

volumes:
  postgres_data:
