version: "3.9"

services:
  hr_recruiting_assistant_adk:
    build: .
    container_name: hr_recruiting_assistant_adk
    ports:
      # Map container port 8006 to host port 8006 (or choose another host port)
      - "8007:8007"
    networks:
      # Connect to the existing network used by the platform services
      - agents_net
    environment:
      # Pass necessary environment variables (URLs, GCP config)
      # These will override defaults in config.py if set
      - AUTH_AGENT_URL=http://auth_agent:8000/a2a
      - WEBSERVICE_AGENT_URL=http://webservice_agent:8000/a2a
      - DBSERVICE_AGENT_URL=http://dbservice_agent:8000/a2a
      # Add GCP_PROJECT_ID, GCP_LOCATION etc. if needed for ADK authentication/operation
      # - GCP_PROJECT_ID=your-gcp-project-id
      # - GCP_LOCATION=us-central1
      # Make sure the container has credentials (e.g., via mounted service account key or Workload Identity)
    # Optional: Mount GCP credentials if using a service account key file
    # volumes:
    #   - /path/to/your/gcp-key.json:/app/gcp-key.json:ro
    #   - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json

networks:
  agents_net:
    # This network must already exist (created by the platform-setup_repo docker-compose)
    external: true